In [5]:
from sklearn import linear_model
import pandas as pd
import numpy as np

In [6]:
tips = pd.read_csv('tips.csv')
lr = linear_model.LinearRegression()
predicted = lr.fit(X=tips['total_bill'], y =tips['tip'])

ValueError: Expected 2D array, got 1D array instead:
array=[16.99 10.34 21.01 23.68 24.59 25.29  8.77 26.88 15.04 14.78 10.27 35.26
 15.42 18.43 14.83 21.58 10.33 16.29 16.97 20.65 17.92 20.29 15.77 39.42
 19.82 17.81 13.37 12.69 21.7  19.65  9.55 18.35 15.06 20.69 17.78 24.06
 16.31 16.93 18.69 31.27 16.04 17.46 13.94  9.68 30.4  18.29 22.23 32.4
 28.55 18.04 12.54 10.29 34.81  9.94 25.56 19.49 38.01 26.41 11.24 48.27
 20.29 13.81 11.02 18.29 17.59 20.08 16.45  3.07 20.23 15.01 12.02 17.07
 26.86 25.28 14.73 10.51 17.92 27.2  22.76 17.29 19.44 16.66 10.07 32.68
 15.98 34.83 13.03 18.28 24.71 21.16 28.97 22.49  5.75 16.32 22.75 40.17
 27.28 12.03 21.01 12.46 11.35 15.38 44.3  22.42 20.92 15.36 20.49 25.21
 18.24 14.31 14.    7.25 38.07 23.95 25.71 17.31 29.93 10.65 12.43 24.08
 11.69 13.42 14.26 15.95 12.48 29.8   8.52 14.52 11.38 22.82 19.08 20.27
 11.17 12.26 18.26  8.51 10.33 14.15 16.   13.16 17.47 34.3  41.19 27.05
 16.43  8.35 18.64 11.87  9.78  7.51 14.07 13.13 17.26 24.55 19.77 29.85
 48.17 25.   13.39 16.49 21.5  12.66 16.21 13.81 17.51 24.52 20.76 31.71
 10.59 10.63 50.81 15.81  7.25 31.85 16.82 32.9  17.89 14.48  9.6  34.63
 34.65 23.33 45.35 23.17 40.55 20.69 20.9  30.46 18.15 23.1  15.69 19.81
 28.44 15.48 16.58  7.56 10.34 43.11 13.   13.51 18.71 12.74 13.   16.4
 20.53 16.47 26.59 38.73 24.27 12.76 30.06 25.89 48.33 13.27 28.17 12.9
 28.15 11.59  7.74 30.14 12.16 13.42  8.58 15.98 13.42 16.27 10.09 20.45
 13.28 22.12 24.01 15.69 11.61 10.77 15.53 10.07 12.6  32.83 35.83 29.03
 27.18 22.67 17.82 18.78].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [11]:
arr = np.arange(8)
arr.reshape(-1,1)




array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [13]:
predicted = lr.fit(X=tips['total_bill'].values.reshape(-1,1), y =tips['tip'])

predicted.intercept_

0.9202696135546731

In [14]:
predicted.coef_

array([0.10502452])

In [15]:
pred2 = lr.fit(X=tips[['total_bill', 'size']], y = tips['tip'])
pred2.intercept_

0.6689447408125031

In [16]:
pred2.coef_

array([0.09271334, 0.19259779])

In [18]:
tips_dummy = pd.get_dummies(tips[['total_bill', 'size', 'smoker', 'day', 'time']])
tips_dummy


total_bill  size  smoker_No  smoker_Yes  day_Fri  day_Sat  day_Sun  \
0         16.99     2       True       False    False    False     True   
1         10.34     3       True       False    False    False     True   
2         21.01     3       True       False    False    False     True   
3         23.68     2       True       False    False    False     True   
4         24.59     4       True       False    False    False     True   
..          ...   ...        ...         ...      ...      ...      ...   
239       29.03     3       True       False    False     True    False   
240       27.18     2      False        True    False     True    False   
241       22.67     2      False        True    False     True    False   
242       17.82     2       True       False    False     True    False   
243       18.78     2       True       False    False    False    False   

     day_Thur  time_Dinner  time_Lunch  
0       False         True       False  
1       False         True       False  
2       False         True       False  
3       False         True       False  
4       False         True       False  
..        ...          ...         ...  
239     False         True       False  
240     False         True       False  
241     False         True       False  
242     False         True       False  
243      True         True       False  

[244 rows x 10 columns]

In [20]:
tips_dummy_ref = pd.get_dummies(tips[['total_bill', 'size', 'smoker', 'day', 'time']],
drop_first=True)
tips_dummy_ref

total_bill  size  smoker_Yes  day_Sat  day_Sun  day_Thur  time_Lunch
0         16.99     2       False    False     True     False       False
1         10.34     3       False    False     True     False       False
2         21.01     3       False    False     True     False       False
3         23.68     2       False    False     True     False       False
4         24.59     4       False    False     True     False       False
..          ...   ...         ...      ...      ...       ...         ...
239       29.03     3       False     True    False     False       False
240       27.18     2        True     True    False     False       False
241       22.67     2        True     True    False     False       False
242       17.82     2       False     True    False     False       False
243       18.78     2       False    False    False      True       False

[244 rows x 7 columns]

In [22]:
lr3 = linear_model.LinearRegression()
pred3 = lr3.fit(X=tips_dummy_ref, y = tips['tip'])
pred3

LinearRegression()

In [24]:
values = np.append(pred3.intercept_, pred3.coef_)
names = np.append('intercept', tips_dummy_ref.columns)
results3 = pd.DataFrame(values, index=names, columns = ['coef'])
results3

coef
intercept   0.789582
total_bill  0.094277
size        0.176374
smoker_Yes -0.086470
day_Sat    -0.125864
day_Sun    -0.032578
day_Thur   -0.160946
time_Lunch  0.068146